apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260529-155201-44t0isiv5fw7-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260529-155201-44t0isiv5fw7.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260529-155201-44t0isiv5fw7-service
            port:
              number: 80
