apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260529-155201-44t0isiv5fw7-service
spec:
  selector:
    app: enterprise-system-20260529-155201-44t0isiv5fw7
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
